version: '3.7'

services:

  api:
    ports:
      - 5678:5678
    command: 
    - "sh"
    - "-c"
    - |-
      pip install debugpy -t /tmp && python /tmp/debugpy \
      --listen 0.0.0.0:5678 \
      -m flask run --host=0.0.0.0

  worker:
    ports:
      - 5680:5680
    command: 
      - "sh"
      - "-c"
      - |-
        pip install debugpy -t /tmp && python /tmp/debugpy \
        --listen 0.0.0.0:5680 \
        -m celery -A app.celery worker -l info
